package com.fleetwise.api.activity.entity;

public enum ActivityAction {
    FLEET_CREATED,
    VEHICLE_CREATED,
    VEHICLE_UPDATED,
    MAINTENANCE_CREATED,
    MAINTENANCE_COMPLETED,
    MAINTENANCE_CANCELLED,
    FUEL_LOG_CREATED,
    ALERT_RESOLVED,
    DOCUMENT_UPLOADED,
    DOCUMENT_DELETED,
    AI_SUMMARY_GENERATED
}