package com.fleetwise.api.alert.entity;

public enum AlertType {
    MAINTENANCE_DUE,
    MAINTENANCE_OVERDUE,
    HIGH_FUEL_COST,
    MISSING_MILEAGE_UPDATE,
    INSPECTION_REMINDER,
    FUEL_ANOMALY,
    LOW_FUEL,
    ENGINE_OVERHEAT,
    LOW_BATTERY,
    SPEEDING,
    EXCESSIVE_IDLE,
    CHECK_ENGINE
}
